django/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pollugraphics/', include('pollugraphics.urls', namespace="pollugraphics", app_name='pollugraphics')),
)

django/pollugraphics/urls.py
from django.conf.urls import patterns, url
from pollugraphics import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^county/(?P<county_id>\d+)/$', views.county, name='county'),
	url(r'^facility/(?P<facility_id>\d+)/$', views.facility, name='facility'),
    url(r'^county/(?P<county_id>\d+)/(?P<pollutant>\w+)/$', views.countyPollution, name='countyPollution'),
	url(r'^county/similar/(?P<county_id>\d+)/', views.compare_county, name='compare_county'),
	url(r'^compare/(?P<county_id1>\d+)&(?P<county_id2>\d+)/', views.compare, name='compare'),
    url(r'^facility_search/$', views.facility_search, name='facility_search'),
    url(r'^search/$', views.search, name='search')
)

django/pollugraphics/models.py
from django.db import models
from django import forms

class State(models.Model):
	abbreviation = models.CharField(max_length=2, primary_key=True)
	name = models.CharField(max_length=20)

	class Meta:
		db_table = 'state'

	def __unicode__(self):
		return self.abbreviation

class County(models.Model):
	name = models.CharField(max_length=50)
	state = models.ForeignKey(State)
	population_density = models.DecimalField(decimal_places=2, max_digits=20)
	unemployment_rate = models.DecimalField(decimal_places=2, max_digits=20)
	median_income = models.DecimalField(decimal_places=2, max_digits=20)
	percent_hs = models.DecimalField(decimal_places=2, max_digits=20)
	percent_bachelors = models.DecimalField(decimal_places=2, max_digits=20)

	class Meta:
		db_table = 'county'
	
	def __unicode__(self):
		return self.name + ' County (' + self.state.name + ')'

class Facility(models.Model):
	eis_id = models.IntegerField(primary_key=True)
	name = models.CharField(max_length=200)
	address = models.CharField(max_length=200, null=True, blank=True)
	city = models.CharField(max_length=200, null=True, blank=True)
	county = models.CharField(max_length=50)
	state = models.ForeignKey(State)
	industry = models.CharField(max_length=200, null=True, blank=True)
	latitude = models.DecimalField(decimal_places=10, max_digits=20, null=True, blank=True)
	longitude = models.DecimalField(decimal_places=10, max_digits=20, null=True, blank=True)

	class Meta:
		db_table = 'facility'
	
	def __unicode__(self):
		return self.name

class FacilityPollution(models.Model):
	eis_id = models.ForeignKey(Facility, primary_key=True)
	carbon_monoxide = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)
	nitrogen_oxides = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)
	sulfur_dioxide = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)
	particulate_matter_10 = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)
	lead = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)
	mercury = models.DecimalField(decimal_places=5, max_digits=20, null=True, blank=True)

	class Meta:
		db_table = 'facilitypollution'

class CountyAttributesForm(forms.Form):
	same_state = forms.BooleanField(required=False)
	population_density = forms.BooleanField(required=False)
	unemployment_rate = forms.BooleanField(required=False)
	median_income = forms.BooleanField(required=False)
	percent_hs = forms.BooleanField(required=False)
	percent_bachelors = forms.BooleanField(required=False)

django/pollugraphics/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from pollugraphics.models import County, State, Facility, FacilityPollution, CountyAttributesForm
from django.db import connection

def index(request):
	counties = County.objects.order_by('state__name', 'name')
	states = State.objects.order_by('abbreviation')
	template = loader.get_template('pollugraphics/index.html')
	context = RequestContext(request, {
		'counties' : counties,
		'states' : states,
	})
	return HttpResponse(template.render(context))

def facility_search(request):
	return render(request, 'facility_search.html')

def search(request):
	error = False
	if "facilityChoice" in request.GET:
		facilityChoice = request.GET['facilityChoice']
		if not facilityChoice:
			error = True
		else:
			facility = Facility.objects.filter(name__icontains=facilityChoice)
			return render(request, 'pollugraphics/facility_search.html',
				      {'facilities': facility, 'query': facilityChoice})
	return render(request, 'pollugraphics/facility_search.html', {'error': True})

def county(request, county_id):
	if request.is_ajax():
		if request.GET.get('action') == 'compare':
			comps = County.objects.raw('SELECT id, name FROM County LIMIT 5')
			json = simplejson.dumps(comps, cls=DjangoJSONEncoder)
			return HttpResponse(json, mimetype='application/json')
	
	c = get_object_or_404(County, pk=county_id)
	cursor = connection.cursor()
	cursor.execute('SELECT sum(carbon_monoxide), sum(nitrogen_oxides), sum(sulfur_dioxide), sum(particulate_matter_10), sum(lead), sum(mercury), count(*), count(carbon_monoxide),count(nitrogen_oxides), count(sulfur_dioxide), count(particulate_matter_10), count(lead), count(mercury) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])
	row = cursor.fetchone()
	if(row is None):
		row = tuple([0]*13)
	else:
		row = tuple((x if x is not None else 0 for x in row))

	return render(request, 'pollugraphics/county.html', {
		'county': c,
		'aggPollution': row,
		'form': CountyAttributesForm(request.POST)
		})

def compare(request, county_id1, county_id2):
	c1 = get_object_or_404(County, pk=county_id1)
	c2 = get_object_or_404(County, pk=county_id2)
	cursor = connection.cursor()
	cursor.execute('SELECT sum(carbon_monoxide), sum(nitrogen_oxides), sum(sulfur_dioxide), sum(particulate_matter_10), sum(lead), sum(mercury), count(*), count(carbon_monoxide),count(nitrogen_oxides), count(sulfur_dioxide), count(particulate_matter_10), count(lead), count(mercury) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id1])
	row1 = cursor.fetchone();
	if(row1 is None):
		row1 = tuple([0]*13)
	else:
		row1 = tuple((x if x is not None else 0 for x in row1))

	cursor.execute('SELECT sum(carbon_monoxide), sum(nitrogen_oxides), sum(sulfur_dioxide), sum(particulate_matter_10), sum(lead), sum(mercury), count(*), count(carbon_monoxide),count(nitrogen_oxides), count(sulfur_dioxide), count(particulate_matter_10), count(lead), count(mercury) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id2])
	row2 = cursor.fetchone();
	if(row2 is None):
		row2 = tuple([0]*13)
	else:
		row2 = tuple((x if x is not None else 0 for x in row2))

	return render(request, 'pollugraphics/compare.html', {
		'county1': c1,
		'county2': c2,
		'aggPollution1': row1,
		'aggPollution2': row2
		})
		
def compare_county(request, county_id, limit=5):
	c = get_object_or_404(County, pk=county_id)
	same_state = request.GET.get('state', '')
	sort_by = request.GET.get('sort', '')

	if same_state == 'yes':
		comps = County.objects.raw('SELECT * FROM County WHERE state_id = \'%s\' AND id != %s ORDER BY abs((SELECT %s FROM County WHERE id = %s) - %s) LIMIT %d;' % (c.state, c.id, sort_by, county_id, sort_by, limit))
	else:
		comps = County.objects.raw('SELECT * FROM County WHERE id != %s ORDER BY abs((SELECT %s FROM County WHERE id = %s) - %s) LIMIT %d;' % (c.id, sort_by, county_id, sort_by, limit))
		
	return render(request, 'pollugraphics/similar_counties.html', {
		'county': c,
		'comps': comps,
		})
	
def facility(request, facility_id):
	f = get_object_or_404(Facility, pk=facility_id)
	fp = get_object_or_404(FacilityPollution, pk=facility_id)
	return render(request, 'pollugraphics/facility.html', {
		'facility': f,
		'facilitypollution': fp
		})

def countyPollution(request, county_id, pollutant):
	c = get_object_or_404(County, pk=county_id)
	cursor = connection.cursor()
	if pollutant=='CO':
		cursor.execute('SELECT sum(carbon_monoxide), count(carbon_monoxide) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])
		return render(request, 'pollugraphics/pollutant.html',{
	       'polluters': Facility.objects.raw('SELECT Facility.eis_id, Facility.name, Facility.city, FacilityPollution.carbon_monoxide AS pollute FROM County, Facility, FacilityPollution WHERE Facility.eis_id = FacilityPollution.eis_id_id AND Facility.county=County.name AND Facility.state_id=County.state_id AND County.id=%s AND FacilityPollution.carbon_monoxide>0 ORDER BY FacilityPollution.carbon_monoxide DESC LIMIT 10;', [county_id]),
	       'county': c,
	       'pollutant': pollutant,
		   'aggPollutant': cursor.fetchone()
	        })
	elif pollutant=='NOx':
		cursor.execute('SELECT sum(nitrogen_oxides), count(nitrogen_oxides) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])	
		return render(request, 'pollugraphics/pollutant.html',{
	       'polluters': Facility.objects.raw('SELECT Facility.eis_id, Facility.name, Facility.city, FacilityPollution.nitrogen_oxides AS pollute FROM County, Facility, FacilityPollution WHERE Facility.eis_id = FacilityPollution.eis_id_id AND Facility.county=County.name AND Facility.state_id=County.state_id AND County.id=%s AND FacilityPollution.nitrogen_oxides>0 ORDER BY FacilityPollution.nitrogen_oxides DESC LIMIT 10;', [county_id]),
	       'county': c,
	       'pollutant': pollutant,
		   'aggPollutant': cursor.fetchone()
	        })
	elif pollutant=='SO2':
		cursor.execute('SELECT sum(sulfur_dioxide), count(sulfur_dioxide) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])	
		return render(request, 'pollugraphics/pollutant.html',{
	       'polluters': Facility.objects.raw('SELECT Facility.eis_id, Facility.name, Facility.city, FacilityPollution.sulfur_dioxide AS pollute FROM County, Facility, FacilityPollution WHERE Facility.eis_id = FacilityPollution.eis_id_id AND Facility.county=County.name AND Facility.state_id=County.state_id AND County.id=%s AND FacilityPollution.sulfur_dioxide>0 ORDER BY FacilityPollution.sulfur_dioxide DESC LIMIT 10;', [county_id]),
	       'county': c,
	       'pollutant': pollutant,
		   'aggPollutant': cursor.fetchone()
	        })
	elif pollutant=='PM10':
		cursor.execute('SELECT sum(particulate_matter_10), count(particulate_matter_10) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])		
		return render(request, 'pollugraphics/pollutant.html',{
	       'polluters': Facility.objects.raw('SELECT Facility.eis_id, Facility.name, Facility.city, FacilityPollution.particulate_matter_10 AS pollute FROM County, Facility, FacilityPollution WHERE Facility.eis_id = FacilityPollution.eis_id_id AND Facility.county=County.name AND Facility.state_id=County.state_id AND County.id=%s AND FacilityPollution.particulate_matter_10>0 ORDER BY FacilityPollution.particulate_matter_10 DESC LIMIT 10;', [county_id]),
	       'county': c,
	       'pollutant': pollutant,
		   'aggPollutant': cursor.fetchone()
	        })
	elif pollutant=='lead':
		cursor.execute('SELECT sum(lead), count(lead) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])		
		return render(request, 'pollugraphics/pollutant.html',{
	       'polluters': Facility.objects.raw('SELECT Facility.eis_id, Facility.name, Facility.city, FacilityPollution.lead AS pollute FROM County, Facility, FacilityPollution WHERE Facility.eis_id = FacilityPollution.eis_id_id AND Facility.county=County.name AND Facility.state_id=County.state_id AND County.id=%s AND FacilityPollution.lead>0 ORDER BY FacilityPollution.lead DESC LIMIT 10;', [county_id]),
	       'county': c,
	       'pollutant': pollutant,
		   'aggPollutant': cursor.fetchone()
	        })
	elif pollutant=='mercury':
		cursor.execute('SELECT sum(mercury), count(mercury) FROM County, Facility, FacilityPollution WHERE County.id = %s AND County.name = Facility.county AND County.state_id = Facility.state_id AND Facility.eis_id = FacilityPollution.eis_id_id GROUP BY County.name;',[county_id])			
		return render(request, 'pollugraphics/pollutant.html',{

django/pollugraphics/templates/pollugraphics/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>pollugraphics</title>
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
		<style>
			.footer {
				margin-top: 20px;		
			}
			#content{
				height: 100%;
			}
			#left {
				float: left;
				width: 50%;
				height: 100%;
			}
			#right {
				float: left;
				width: 50%;
				height: 100%;
			}
		</style>
		<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
		<a href="{% url 'pollugraphics:index'%}"><img src="http://i.imgur.com/uI9BAKY.png"/ style="max-width:50%; max-height:50%; margin-left:20px"></a>
	</head>
	<body>
	<div class="container">
		<h1>{% block heading %}{% endblock %}</h1>

		<div id="content">
			{% block content %}{% endblock %}
		</div>
	
		<div class="footer">
			<p class="muted pagination-centered">Created by: Peggy Li, Austin Lu &amp; Lawrence Lin</p>
		</div>
	</div>
	</body>
</html>

django/pollugraphics/templates/pollugraphics/compare.html
{% extends "pollugraphics/base.html" %}

{% block content %}
<div id="content">
<div id="left">
<h1>{{county1.name}} County, {{county1.state.name}}</h1>

<!-- county demographics data -->
<h2>Demographic Data</h2>

<ul>
	<li>Population density: {{county1.population_density}}</li>
	<li>Median income: {{county1.median_income}}</li>
	<li>Unemployment rate: {{county1.unemployment_rate}}</li>
	<li>% with high school degree: {{county1.percent_hs}}</li>
	<li>% with bachelors degree: {{county1.percent_bachelors}}</li>
</ul>

<!-- county pollution data -->
<h2>Industrial Pollution Data</h2>
<ul>
	<li><span id="1C">Carbon monoxide (tons): </span>{{aggPollution1.0}} from <b><a href="../../county/{{county1.id}}/CO">{{aggPollution1.7}} facilit{{ aggPollution1.7 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="1N">Nitrogen oxides (tons): </span>{{aggPollution1.1}} from <b><a href="../../county/{{county1.id}}/NOx">{{aggPollution1.8}} facilit{{ aggPollution1.8 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="1S">Sulfur dioxide (tons): </span>{{aggPollution1.2}} from <b><a href="../../county/{{county1.id}}/SO2">{{aggPollution1.9}} facilit{{ aggPollution1.7 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="1P">Particulate matter PM-10 (tons): </span>{{aggPollution1.3}} from <b><a href="../../county/{{county1.id}}/PM10">{{aggPollution1.10}} facilit{{ aggPollution1.10 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="1L">Lead (tons): </span>{{aggPollution1.4}} from <b><a href="../../county/{{county1.id}}/lead">{{aggPollution1.11}} facilit{{ aggPollution1.11 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="1M">Mercury (lbs): </span>{{aggPollution1.5}} from <b><a href="../../county/{{county1.id}}/mercury">{{aggPollution1.12}} facilit{{ aggPollution1.12 |pluralize:"y,ies" }}</a></b> </li>
	
</ul>
<h3>Find similar counties based on:</h3> 
<form action="{% url 'pollugraphics:compare_county' county1.id %}" method="get">
	<!-- {{ form.as_p }} -->
	<!-- select whether or not to impose same-state restriction -->
	<label>Restrict search to same state as {{ county1.name }} County? </label>
	<input type="radio" name="state" value="yes">Yes
	<input type="radio" name="state" value="no">No
	<br/>
	<!-- select a single attribute to sort by -->
	<label>Compare by:</label>
	<select name="sort">
		<option value="population_density">Population Density</option>
		<option value="median_income">Median Income</option>
		<option value="unemployment_rate">Unemployment Rate</option>
		<option value="percent_hs">Percent with HS Degree</option>
		<option value="percent_bachelors">Percent with Bachelors Degree</option>
	</select>
	<input id="submit" type="submit" value="Find similar counties" />
</form>
</div>

<div id="right">
<!-- county name and state -->
<h1>{{county2.name}} County, {{county2.state.name}}</h1>

<!-- county demographics data -->
<h2>Demographic Data</h2>

<ul>
	<li>Population density: {{county2.population_density}}</li>
	<li>Median income: {{county2.median_income}}</li>
	<li>Unemployment rate: {{county2.unemployment_rate}}</li>
	<li>% with high school degree: {{county2.percent_hs}}</li>
	<li>% with bachelors degree: {{county2.percent_bachelors}}</li>
</ul>

<!-- county pollution data -->
<h2>Industrial Pollution Data</h2>
<ul>
	<li><span id="2C">Carbon monoxide (tons): </span>{{aggPollution2.0}} from <b><a href="../../county/{{county2.id}}/CO">{{aggPollution2.7}} facilit{{ aggPollution2.7 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="2N">Nitrogen oxides (tons): </span>{{aggPollution2.1}} from <b><a href="../../county/{{county2.id}}/NOx">{{aggPollution2.8}} facilit{{ aggPollution2.8 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="2S">Sulfur dioxide (tons): </span>{{aggPollution2.2}} from <b><a href="../../county/{{county2.id}}/SO2">{{aggPollution2.9}} facilit{{ aggPollution2.9 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="2P">Particulate matter PM-10 (tons): </span>{{aggPollution2.3}} from <b><a href="../../county/{{county2.id}}/PM10">{{aggPollution2.10}} facilit{{ aggPollution2.10 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="2L">Lead (tons): </span>{{aggPollution2.4}} from <b><a href="../../county/{{county2.id}}/lead">{{aggPollution2.11}} facilit{{ aggPollution2.11 |pluralize:"y,ies" }}</a></b> </li>
	<li><span id="2M">Mercury (lbs): </span>{{aggPollution2.5}} from <b><a href="../../county/{{county2.id}}/mercury">{{aggPollution2.12}} facilit{{ aggPollution2.12 |pluralize:"y,ies" }}</a></b> </li>
	
</ul>
<h3>Find similar counties based on:</h3> 
<form action="{% url 'pollugraphics:compare_county' county2.id %}" method="get">
	<!-- {{ form.as_p }} -->
	<!-- select whether or not to impose same-state restriction -->
	<label>Restrict search to same state as {{ county2.name }} County? </label>
	<input type="radio" name="state" value="yes">Yes
	<input type="radio" name="state" value="no">No
	<br/>
	<!-- select a single attribute to sort by -->
	<label>Compare by:</label>
	<select name="sort">
		<option value="population_density">Population Density</option>
		<option value="median_income">Median Income</option>
		<option value="unemployment_rate">Unemployment Rate</option>
		<option value="percent_hs">Percent with HS Degree</option>
		<option value="percent_bachelors">Percent with Bachelors Degree</option>
	</select>
	<input id="submit" type="submit" value="Find similar counties" />
</form>
</div>

</div>

<script>
document.getElementById("1C").style.color = ({{aggPollution1.0}} > {{aggPollution2.0}}) ? "#B80000" : "#006600";
document.getElementById("1N").style.color = ({{aggPollution1.1}} > {{aggPollution2.1}}) ? "#B80000" : "#006600";
document.getElementById("1S").style.color = ({{aggPollution1.2}} > {{aggPollution2.2}}) ? "#B80000" : "#006600";
document.getElementById("1P").style.color = ({{aggPollution1.3}} > {{aggPollution2.3}}) ? "#B80000" : "#006600";
document.getElementById("1L").style.color = ({{aggPollution1.4}} > {{aggPollution2.4}}) ? "#B80000" : "#006600";
document.getElementById("1M").style.color = ({{aggPollution1.5}} > {{aggPollution2.5}}) ? "#B80000" : "#006600";
document.getElementById("2C").style.color = ({{aggPollution1.0}} >= {{aggPollution2.0}}) ? "#006600" : "#B80000";
document.getElementById("2N").style.color = ({{aggPollution1.1}} >= {{aggPollution2.1}}) ? "#006600" : "#B80000";
document.getElementById("2S").style.color = ({{aggPollution1.2}} >= {{aggPollution2.2}}) ? "#006600" : "#B80000";
document.getElementById("2P").style.color = ({{aggPollution1.3}} >= {{aggPollution2.3}}) ? "#006600" : "#B80000";
document.getElementById("2L").style.color = ({{aggPollution1.4}} >= {{aggPollution2.4}}) ? "#006600" : "#B80000";
document.getElementById("2M").style.color = ({{aggPollution1.5}} >= {{aggPollution2.5}}) ? "#006600" : "#B80000";
</script>
{% endblock %}

django/pollugraphics/templates/pollugraphics/facility_search.html
{% extends "pollugraphics/base.html" %}
{% block heading %}
Facility Search
{% endblock %}

{% block content %}
{% if error %}
        <p style="color: red;">Please submit a search term.</p>
	Go back to <a href="{% url 'pollugraphics:index' %}">Home page</a>
{% else %}
<p>You searched for: <strong>{{ query }}</strong></p>

{% if facilities %}
    <p>Found {{ facilities|length }} facilities.</p>
    <ul>
        {% for facility in facilities %}
        <li><a href="{% url 'pollugraphics:facility' facility.eis_id %} ">{{ facility.name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No facilities matched your search criteria.</p>
{% endif %}

Back to <a href="{% url 'pollugraphics:index' %}">Home page</a>
{% endif %}
{% endblock %}

django/pollugraphics/templates/pollugraphics/index.html
{% extends "pollugraphics/base.html" %}
  
{% block content %}
<h2>Look up one county</h2>
<form>
<select name="county" id = "countyChoice">
{% for c in counties %}
        <option value="{{ c.id }}">{{ c }}</option>
{% endfor %}
</select>
<input type="button" id="submitButton" value="Submit">
</form>

<script>

var submitButton = document.getElementById("submitButton");

submitButton.onclick=function(){
	var e = document.getElementById("countyChoice");
	var countyid = e.options[e.selectedIndex].value;
	window.location.href = "county/" + countyid;
}     
</script>

<br><br><br>

<h2>Search by facility</h2>

{% if error %}
        <p style="color: red;">Please submit a search term.</p>
{% endif %}

<form action="{% url 'pollugraphics:search' %}" method="get">
Facility name:<input type="text" name="facilityChoice">
<input type="submit" value="Submit">
</form>

{% endblock %}

django/pollugraphics/templates/pollugraphics/pollutant.html
{% extends "pollugraphics/base.html" %}

<!-- county name and state -->
{% block heading %}{{county.name}} County, {{county.state.name}}{% endblock %}
{% block content %}
<script type="text/javascript" src="//www.google.com/jsapi"></script>
<script type="text/javascript">
	var chartArr = [];
	chartArr.push(['Facility name', '{{pollutant}} emission']);
	var aggPollutantLeft = parseFloat("{{aggPollutant.0}}");
	var aggFacilitiesLeft = parseInt("{{aggPollutant.1}}");
</script>

<!-- county demographics data -->
<h2>Top 10 polluters of {{pollutant}}</h2>
<table cellpadding="5%">
<tr><th>Facility name</th><th>City</th><th>{{pollutant}} emission</th></tr>
{% for p in polluters %}
    <tr><td><a href="{% url 'pollugraphics:facility' p.eis_id %}">{{p.name}}</a></td><td>{{p.city}}</td><td>{{p.pollute.normalize}}</td><tr>
	<script type="text/javascript">
		chartArr.push(['{{p.name}}', parseFloat("{{p.pollute}}")]);
		aggPollutantLeft -= parseFloat("{{p.pollute}}");
		aggFacilitiesLeft--;
	</script>
{% endfor %}
</table>

<div id="visualization" style="width: 600px; height: 400px;"></div>
Back to <a href="{% url 'pollugraphics:county' county.id %}">county</a>

<script type="text/javascript">
  google.load('visualization', '1', {packages: ['corechart']});
</script>
<script type="text/javascript">

	function drawVisualization() {
		// Create and draw the visualization.
		if(aggFacilitiesLeft>0 && aggPollutantLeft>0){
			chartArr.push([aggFacilitiesLeft+' other facilities', aggPollutantLeft]); //undisplayed facilities
		}
		var data = google.visualization.arrayToDataTable(chartArr);
		new google.visualization.PieChart(document.getElementById('visualization')).
			draw(data, {title:"{{county.name}} County {{pollutant}} emissions by facility"});
	}
	google.setOnLoadCallback(drawVisualization);
</script>
{% endblock %}